### ISSUE TITLE
New Feature: Build CreatePostView

### ISSUE THREAD

**Issue by andrewkykoo** [andrewkykoo/mingle-ios#1]
At the moment, Channel view only displays a list of posts. It should also allow users to add a post to the current channel. 

Desired functionalities / specs:

1. Create a button that is preferably positioned in the top right corner and displays a form where the user can enter subject and content. The form could be of a modal or a completely separate view type. 
2. Once the user submits the form, the user should be taken back to the channel view that will display existing posts as well as the newly created post.

**Comment by WasifRaza123** [comment]
Hi @andrewkykoo , I cannot see the design for the form and button in Figma?

**Comment by andrewkykoo** [comment]
hi @WasifRaza123, this project is no longer available. Please check out my other project [https://github.com/andrewkykoo/Connect](url) and feel free to create an issue for enhancements and new features as sketched in the figma file.
